#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config top_padding 24

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color '#8fa1b3'
bspc config normal_border_color '#2B303B'

xsetroot -cursor_name left_ptr

# I will need this soon.
# bspc config click_to_focus true

bspc monitor -d ❶ ❷ ❸ ❹ ❺

feh --bg-scale ~/Images/by_billboards_2560.jpg
compton --config ~/.config/compton/compton.conf -b
tint2 &
dropbox &
pnmixer &
udiskie -N --tray &
nm-applet &
