#!/bin/sh

status=`acpi -V | grep -E 'Battery 0: Charging|Discharging' | awk '{match($0,"Charging|Discharging",a)}END{print a[0]}'`

if [ "$status" == "Discharging" ]; then
    echo -e '\uf240 '
else
    echo -e '\uf1e6 '
fi
